sudo: false
language: python
matrix:
  include:
    - python: 
      - '3.6'
      - '3.7'
      install:
        - pip install .
        - pip install flake8
        - pip install pytest
        - pip install pytest-flake8
      script:
        - flake8
        - pytest
